apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: multi-cloud-monitor
spec:
  selector:
    matchLabels:
      app: multi-cloud-app
  endpoints:
    - port: http
      interval: 30s